//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.25 at 01:37:46 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        xmlns = {
                @XmlNs(prefix="ns0", namespaceURI="http://schemas.microsoft.com/xrm/2011/Contracts/Services"),
                @XmlNs(prefix="ns1", namespaceURI="http://schemas.datacontract.org/2004/07/System.Collections.Generic"),
                @XmlNs(prefix="ns2", namespaceURI="http://schemas.microsoft.com/2003/10/Serialization/Arrays"),
                @XmlNs(prefix="ns3", namespaceURI="http://schemas.microsoft.com/xrm/2011/Metadata"),
                @XmlNs(prefix="ns4", namespaceURI="http://schemas.microsoft.com/xrm/2011/Contracts"),
                @XmlNs(prefix="ns5", namespaceURI="http://schemas.microsoft.com/2003/10/Serialization/"),
                @XmlNs(prefix="xsi", namespaceURI="http://www.w3.org/2001/XMLSchema-instance")
        })
package Create;

import javax.xml.bind.annotation.XmlNs;